In [1]:
import pandas as pd
import numpy as np

### Pandas, EDA

In [2]:
data = pd.read_csv('TopAnimatedImDb.csv')
data.head()

Title  Rating      Votes     Gross  \
0      Sen to Chihiro no kamikakushi     8.6    747,148   $10.06M   
1                      The Lion King     8.5  1,041,158  $422.78M   
2                     Hotaru no haka     8.5    272,469       NaN   
3                     Kimi no na wa.     8.4    259,975    $5.02M   
4  Spider-Man: Into the Spider-Verse     8.4    510,227  $190.24M   

                Genre  Metascore Certificate         Director  Year  \
0   Adventure, Family       96.0           U   Hayao Miyazaki  2001   
1    Adventure, Drama       88.0           U     Roger Allers  1994   
2          Drama, War       94.0           U    Isao Takahata  1988   
3      Drama, Fantasy       79.0           U   Makoto Shinkai  2016   
4   Action, Adventure       87.0           U  Bob Persichetti  2018   

                                         Description  Runtime  
0  ["\nDuring her family's move to the suburbs, a...  125 min  
1  ['\nLion prince Simba and his father are targe...   88 min  
2  ['\nA young boy and his little sister struggle...   89 min  
3  ['\nTwo strangers find themselves linked in a ...  106 min  
4  ['\nTeen Miles Morales becomes the Spider-Man ...  117 min

In [3]:
data.shape

(85, 11)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Title        85 non-null     object 
 1   Rating       85 non-null     float64
 2   Votes        85 non-null     object 
 3   Gross        50 non-null     object 
 4   Genre        85 non-null     object 
 5   Metascore    80 non-null     float64
 6   Certificate  84 non-null     object 
 7   Director     85 non-null     object 
 8   Year         85 non-null     int64  
 9   Description  85 non-null     object 
 10  Runtime      85 non-null     object 
dtypes: float64(2), int64(1), object(8)
memory usage: 7.4+ KB


In [5]:
data.isnull().sum()

Title           0
Rating          0
Votes           0
Gross          35
Genre           0
Metascore       5
Certificate     1
Director        0
Year            0
Description     0
Runtime         0
dtype: int64

In [6]:
data[data.Gross.isnull() + data.Metascore.isnull() + data.Certificate.isnull()]

Title  Rating    Votes Gross  \
2                                      Hotaru no haka     8.5  272,469   NaN   
12                 Kimetsu no Yaiba: Mugen Ressha-Hen     8.2   55,255   NaN   
15                                     Koe no katachi     8.1   78,876   NaN   
16                                              Klaus     8.1  146,042   NaN   
17                        Ôkami kodomo no Ame to Yuki     8.1   44,668   NaN   
18                                      Mary and Max.     8.1  176,615   NaN   
24                                        WolfWalkers     8.0   31,618   NaN   
25                                               Soul     8.0  319,513   NaN   
26                                           Zootopia     8.0  490,842   NaN   
27                          Kaguya-hime no Monogatari     8.0   46,319   NaN   
28                                    Song of the Sea     8.0   58,124   NaN   
29                                         Persepolis     8.0   94,517   NaN   
31  Shin seiki Evangelion Gekijô-ban: Air/Magokoro...     8.0   53,842   NaN   
32                                      Pâfekuto burû     8.0   74,701   NaN   
34                               Beauty and the Beast     8.0  450,780   NaN   
35                                              Akira     8.0  184,356   NaN   
36                             Tenkû no shiro Rapyuta     8.0  165,250   NaN   
37                           Kaze no tani no Naushika     8.0  168,233   NaN   
38                                  Fantastic Mr. Fox     7.9  228,963   NaN   
39                                              Shrek     7.9  668,156   NaN   
40                                        Toy Story 2     7.9  574,778   NaN   
41                                   Mimi wo sumaseba     7.9   62,107   NaN   
42                                     Kôkaku Kidôtai     7.9  142,032   NaN   
43                     The Nightmare Before Christmas     7.9  330,540   NaN   
44                           Doragon bôru chô: Burorî     7.8   27,232   NaN   
45                                       Isle of Dogs     7.8  166,539   NaN   
46                                     Loving Vincent     7.8   57,727   NaN   
47                                         Big Hero 6     7.8  456,307   NaN   
48                         How to Train Your Dragon 2     7.8  332,536   NaN   
49                                  Tôkyô goddofâzâzu     7.8   39,951   NaN   
52                                      Jûbê ninpûchô     7.8   37,510   NaN   
54                                  Majo no takkyûbin     7.8  143,013   NaN   
65                                Toki o kakeru shôjo     7.7   66,081   NaN   
71                                    Kurenai no buta     7.7   89,026   NaN   
75                      The Mitchells vs the Machines     7.6  105,707   NaN   

                 Genre  Metascore Certificate           Director  Year  \
2           Drama, War       94.0           U      Isao Takahata  1988   
12   Action, Adventure       72.0          UA     Haruo Sotozaki  2020   
15               Drama       78.0          16       Naoko Yamada  2016   
16   Adventure, Comedy       65.0           7      Sergio Pablos  2019   
17       Drama, Family       71.0           U      Mamoru Hosoda  2012   
18       Comedy, Drama        NaN         NaN        Adam Elliot  2009   
24   Adventure, Family       87.0          UA         Tomm Moore  2020   
25   Adventure, Comedy       83.0           U        Pete Docter  2020   
26   Adventure, Comedy       78.0           U       Byron Howard  2016   
27       Drama, Family       89.0           U      Isao Takahata  2013   
28    Adventure, Drama       85.0          PG         Tomm Moore  2014   
29    Biography, Drama       90.0       PG-13  Vincent Paronnaud  2007   
31       Action, Drama        NaN   Not Rated       Hideaki Anno  1997   
32        Crime, Drama        NaN           A        Satoshi Kon  1997   
34     Family, Fantasy       95.0           U     Gary Tr

In [7]:
data.describe()

Rating  Metascore         Year
count  85.000000  80.000000    85.000000
mean    7.922353  80.850000  2003.211765
std     0.257449   8.965616    15.255830
min     7.600000  59.000000  1937.000000
25%     7.700000  74.000000  1995.000000
50%     7.900000  82.000000  2007.000000
75%     8.100000  87.000000  2014.000000
max     8.600000  96.000000  2021.000000

In [8]:
data.corr()

Rating  Metascore      Year
Rating     1.000000   0.352156  0.105473
Metascore  0.352156   1.000000 -0.204856
Year       0.105473  -0.204856  1.000000

In [9]:
for c in data.columns:
    print(f'Уникальные значения признака {c}:')
    print(data[c].unique())
    print()
    print(f'Количество уникальных значений признака {c}: {len(data[c].unique())}')
    print()

Уникальные значения признака Title:
['Sen to Chihiro no kamikakushi' 'The Lion King' 'Hotaru no haka'
 'Kimi no na wa.' 'Spider-Man: Into the Spider-Verse' 'Coco' 'WALL·E'
 'Mononoke-hime' 'Up' 'Toy Story 3' 'Toy Story' 'Inside Out'
 'Kimetsu no Yaiba: Mugen Ressha-Hen' 'Hauru no ugoku shiro'
 'Finding Nemo' 'Koe no katachi' 'Klaus' 'Ôkami kodomo no Ame to Yuki'
 'Mary and Max.' 'How to Train Your Dragon' 'Ratatouille' 'Monsters, Inc.'
 'The Iron Giant' 'Tonari no Totoro' 'WolfWalkers' 'Soul' 'Zootopia'
 'Kaguya-hime no Monogatari' 'Song of the Sea' 'Persepolis'
 'The Incredibles'
 'Shin seiki Evangelion Gekijô-ban: Air/Magokoro wo, kimi ni'
 'Pâfekuto burû' 'Aladdin' 'Beauty and the Beast' 'Akira'
 'Tenkû no shiro Rapyuta' 'Kaze no tani no Naushika' 'Fantastic Mr. Fox'
 'Shrek' 'Toy Story 2' 'Mimi wo sumaseba' 'Kôkaku Kidôtai'
 'The Nightmare Before Christmas' 'Doragon bôru chô: Burorî'
 'Isle of Dogs' 'Loving Vincent' 'Big Hero 6' 'How to Train Your Dragon 2'
 'Tôkyô goddofâzâzu' 'Se

In [10]:
data.columns = [c.lower() for c in data.columns]
data.columns

Index(['title', 'rating', 'votes', 'gross', 'genre', 'metascore',
       'certificate', 'director', 'year', 'description', 'runtime'],
      dtype='object')

In [11]:
data[data['rating'] > 8.][['title', 'metascore', 'director', 'year']].head(10)

title  metascore         director  year
0      Sen to Chihiro no kamikakushi       96.0   Hayao Miyazaki  2001
1                      The Lion King       88.0     Roger Allers  1994
2                     Hotaru no haka       94.0    Isao Takahata  1988
3                     Kimi no na wa.       79.0   Makoto Shinkai  2016
4  Spider-Man: Into the Spider-Verse       87.0  Bob Persichetti  2018
5                               Coco       81.0      Lee Unkrich  2017
6                             WALL·E       95.0   Andrew Stanton  2008
7                      Mononoke-hime       76.0   Hayao Miyazaki  1997
8                                 Up       88.0      Pete Docter  2009
9                        Toy Story 3       92.0      Lee Unkrich  2010

In [12]:
data[(data['gross'].isnull()) & (data['metascore'].isnull()) & (data['certificate'].isnull())]

title  rating    votes gross           genre  metascore  \
18  Mary and Max.     8.1  176,615   NaN   Comedy, Drama        NaN   

   certificate     director  year  \
18         NaN  Adam Elliot  2009   

                                          description runtime  
18  ['\nA tale of friendship between two unlikely ...  92 min

In [13]:
data['hours'] = [round(float(i.split()[0]) / 60, 2) for i in data['runtime']]
data.head()

title  rating      votes     gross  \
0      Sen to Chihiro no kamikakushi     8.6    747,148   $10.06M   
1                      The Lion King     8.5  1,041,158  $422.78M   
2                     Hotaru no haka     8.5    272,469       NaN   
3                     Kimi no na wa.     8.4    259,975    $5.02M   
4  Spider-Man: Into the Spider-Verse     8.4    510,227  $190.24M   

                genre  metascore certificate         director  year  \
0   Adventure, Family       96.0           U   Hayao Miyazaki  2001   
1    Adventure, Drama       88.0           U     Roger Allers  1994   
2          Drama, War       94.0           U    Isao Takahata  1988   
3      Drama, Fantasy       79.0           U   Makoto Shinkai  2016   
4   Action, Adventure       87.0           U  Bob Persichetti  2018   

                                         description  runtime  hours  
0  ["\nDuring her family's move to the suburbs, a...  125 min   2.08  
1  ['\nLion prince Simba and his father are targe...   88 min   1.47  
2  ['\nA young boy and his little sister struggle...   89 min   1.48  
3  ['\nTwo strangers find themselves linked in a ...  106 min   1.77  
4  ['\nTeen Miles Morales becomes the Spider-Man ...  117 min   1.95

In [14]:
data.groupby(['genre'])['title'].count()

genre
 Action, Adventure     14
 Action, Crime          2
 Action, Drama          2
 Adventure, Comedy     30
 Adventure, Drama       3
 Adventure, Family      7
 Adventure, Fantasy     1
 Adventure, Sci-Fi      1
 Biography, Crime       1
 Biography, Drama       2
 Comedy, Drama          3
 Comedy, Family         1
 Comedy, Fantasy        1
 Crime, Drama           1
 Drama                  1
 Drama, Family          6
 Drama, Fantasy         4
 Drama, War             1
 Family, Fantasy        3
 Sci-Fi                 1
Name: title, dtype: int64

### Numpy

Вычислить A + B, A - B
 
$\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [15]:
A = np.array([[1, -2, 4],
              [2, 0, -1]])
B = np.array([[5, 2, 3],
              [4, 6, 2]])

In [16]:
A + B

array([[6, 0, 7],
       [6, 6, 1]])

In [17]:
A - B

array([[-4, -4,  1],
       [-2, -6, -3]])

Найти матрицу С = A - 3B
 
$\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [18]:
A = np.array([[1, 2],
              [2, -1],
              [3, 0]])
B = np.array([[-1, 1],
              [1, 2],
              [0, 0]])

In [19]:
A - 3 * B

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

Вычислить С = AB
 
$\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [20]:
A = np.array([[1, -1],
              [2, 0],
              [3, 0]])
B = np.array([[1, 1],
              [2, 0]])

In [21]:
A @ B

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

In [22]:
np.dot(A, B)

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

Вычислить определитель матрицы А
 
$\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [23]:
A = np.array([[6, -1, 4],
              [2, 1, 10],
              [8, 0, 2]])

In [24]:
np.linalg.det(A)

-95.99999999999999

Вычислить матрицу, обратную матрице А. И показать, что она действительно является обратной
 
$\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [25]:
A = np.array([[3, 3, -1],
              [4, 1, 3],
              [1, -2, -2]])

In [26]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.07407407,  0.14814815,  0.18518519],
       [ 0.2037037 , -0.09259259, -0.24074074],
       [-0.16666667,  0.16666667, -0.16666667]])

In [27]:
(A @ A_inv).round()

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [-0.,  0.,  1.]])

In [28]:
np.dot(A, A_inv).round()

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [-0.,  0.,  1.]])