In [1]:
import numpy as np

#### 1. Найти A + B:

$A = 
\begin{pmatrix}
1 & 3 & 0\\
2 & -4 & 3\\
5 & 6 & 9
\end{pmatrix}
,\
B = 
\begin{pmatrix}
10 & 6 & -2\\
0 & 7 & 4\\
-1 & 2 & 0
\end{pmatrix}
$

$C_{11} = A_{11} + B_{11} = 1 + 10 = 11$

$C_{12} = A_{12} + B_{12} = 3 + 6 = 9$

$C_{13} = A_{13} + B_{13} = 0 + (-2) = -2$

$C_{21} = A_{21} + B_{21} = 2 + 0 = 2$

$C_{22} = A_{22} + B_{22} = -4 + 7 = 3$

$C_{23} = A_{23} + B_{23} = 3 + 4 = 7$

$C_{31} = A_{31} + B_{31} = 5 + (-1) = 4$

$C_{32} = A_{32} + B_{32} = 6 + 2 = 8$

$C_{33} = A_{33} + B_{33} = 9 + 0 = 9$

$C = A + B = 
\begin{pmatrix}
11 & 9 & -2\\
2 & 3 & 7\\
4 & 8 & 9
\end{pmatrix}
$

При сложении B + A получим тот же результат из-за переместительного закона.

In [2]:
A = np.array([[1, 3, 0],
              [2, -4, 3],
              [5, 6, 9]])
B = np.array([[10, 6, -2],
               [0, 7, 4],
               [-1, 2, 0]])
print('A + B:')
C_1 = A + B
C_2 = B + A
print(C_1)
print()
print('B + A:')
print(C_2)

A + B:
[[11  9 -2]
 [ 2  3  7]
 [ 4  8  9]]

B + A:
[[11  9 -2]
 [ 2  3  7]
 [ 4  8  9]]


#### 1. Найти A * B:

$A = 
\begin{pmatrix}
2 & 8\\
3 & 4
\end{pmatrix}
,\
B = 
\begin{pmatrix}
1 & 0\\
4 & 9
\end{pmatrix}
$

$C_{11} = A_{11} * B_{11} + A_{12} * B_{21} = 2 * 1 + 8 * 4 = 2 + 32 = 34$

$C_{12} = A_{11} * B_{12} + A_{12} * B_{22} = 2 * 0 + 8 * 9 = 0 + 72 = 72$

$C_{21} = A_{21} * B_{11} + A_{22} * B_{21} = 3 * 1 + 4 * 4 = 3 + 16 = 19$

$C_{22} = A_{21} * B_{12} + A_{22} * B_{22} = 3 * 0 + 4 * 9 = 0 + 36 = 36$

$C = A * B = 
\begin{pmatrix}
34 & 72\\
19 & 36
\end{pmatrix}
$

Найдём B * A, так как при умножении матриц друг на друга переместительный закон не работает:

$C_{11} = B_{11} * A_{11} + B_{12} * A_{21} = 1 * 2 + 0 * 3 = 2 + 0 = 2$

$C_{12} = B_{11} * A_{12} + B_{12} * A_{22} = 1 * 8 + 0 * 4 = 8 + 0 = 8$

$C_{21} = B_{21} * A_{11} + B_{22} * A_{21} = 4 * 2 + 9 * 3 = 8 + 27 = 35$

$C_{22} = B_{21} * A_{12} + B_{22} * A_{22} = 4 * 8 + 9 * 4 = 32 + 36 = 68$

$C = B * A = 
\begin{pmatrix}
2 & 8\\
35 & 68
\end{pmatrix}
$

In [3]:
A = np.array([[2, 8],
              [3, 4]])
B = np.array([[1, 0],
              [4, 9]])

print('A * B:')
C_1 = np.dot(A, B)
C_2 = np.dot(B, A)
print(C_1)
print()
print('B * A:')
print(C_2)

A * B:
[[34 72]
 [19 36]]

B * A:
[[ 2  8]
 [35 68]]


#### 3. Вычислить определители:

$
\begin{vmatrix}
3 & 7\\
6 & 9
\end{vmatrix}
$

$\Delta A = A_{11} * A_{22} - A_{12} * A_{21} = 3 * 9 - 7 * 6 = 27 - 42 = -15$

In [4]:
A = np.array([[3, 7],
              [6, 9]])

round(np.linalg.det(A))

-15

$
\begin{vmatrix}
4 & 1 & 9\\
3 & 2 & 0\\
8 & 7 & 5
\end{vmatrix}
$

$\Delta A = A_{11} * A_{22} * A_{33} + A_{12} * A_{23} * A_{31} + A_{13} * A_{21} * A_{32} - 
A_{13} * A_{22} * A_{31} - A_{11} * A_{23} * A_{32} - A_{12} * A_{21} * A_{33}$

$\Delta A = 4 * 2 * 5 + 1 * 0 * 8 + 9 * 3 * 7 - 9 * 2 * 8 - 4 * 0 * 7 - 1 * 3 * 5 = 
40 + 0 + 189 - 144 - 0 - 15 = 70$

Или через миноры:

$
|A| = \
\begin{vmatrix}
4 & 1 & 9\\
3 & 2 & 0\\
8 & 7 & 5
\end{vmatrix}\
=\
A_{11}
\begin{vmatrix}
A_{22} & A_{23}\\
A_{32} & A_{33}
\end{vmatrix}\
-\
A_{12}
\begin{vmatrix}
A_{21} & A_{23}\\
A_{31} & A_{33}
\end{vmatrix}\
+\
A_{13}
\begin{vmatrix}
A_{21} & A_{22}\\
A_{31} & A_{32}
\end{vmatrix}
=\
4
\begin{vmatrix}
2 & 0\\
7 & 5
\end{vmatrix}\
-\
1
\begin{vmatrix}
3 & 0\\
8 & 5
\end{vmatrix}\
+\
9
\begin{vmatrix}
3 & 2\\
8 & 7
\end{vmatrix}
$

$|A| = 4 * (2 * 5 - 0 * 7) - 1 * (3 * 5 - 0 * 8) + 9 * (3 * 7 - 2 * 8) = 4 * 10 - 1 * 15 + 9 * 5 = 40 - 15 + 45 = 70$

In [5]:
A = np.array([[4, 1, 9],
              [3, 2, 0],
              [8, 7, 5]])

round(np.linalg.det(A))

70